#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: Server|Component:<TIER ID>|Custom Metrics|CloudFoundry

numberOfThreads : 10

servers:
  - name: "Server1"
    host: "localhost"
    port: 9000
    user:
    password:
    #encryptedPassword: UmDiudSXVAUSA0ZAT6ycZw==
    #skipSslValidation: true

encryptionKey: Hello

#Supported Values are ORIGIN, DEPLOYMENT and JOB separated by |. Default is ORIGIN|DEPLOYMENT|JOB
#You can change the order or remove one if not needed. DEPLOYMENT|JOB is a valid input.
metricPathComponents: ORIGIN|DEPLOYMENT|JOB
