## Placeholder for a config.yml. These details are fetched from the tile's environment variables.

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<TIERID>|Custom Metrics|PCF|"

numberOfThreads: 10

server:
  name:
  host:
  port:



